// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfzbpjbcqczpudfcocsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmemJwamJjcWN6cHVkZmNvY3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzkzMDMsImV4cCI6MjA2MTE1NTMwM30.Qn13_9M98n0fzgEfKuYeKwfXtPVjYMhdBaX7Ee_yBnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);